tap 'homebrew/core'
tap 'homebrew/cask'

# tools
brew 'ansifilter'
brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'docker-compose'
brew 'findutils'
brew 'gettext'
brew 'ghq'
brew 'hub'
brew 'jq'
brew 'peco'
brew 'readline'
brew 'ssh-copy-id'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'ack'
brew 'mas'
brew 'awscli'
brew 'grpcurl'
brew 'direnv'

tap 'weaveworks/tap'
brew 'weaveworks/tap/eksctl'

# fonts
tap 'sanemat/font'
brew 'sanemat/font/ricty', args: ['with-powerline']
tap 'homebrew/cask-fonts'
brew 'homebrew/cask-fonts/font-myrica'

# Shell integrations
brew 'reattach-to-user-namespace'
brew 'source-highlight'
brew 'tmux'
brew 'z'
brew 'zplug'
brew 'zsh'

# Programming languages
brew 'clang-format'
brew 'plenv'
brew 'pyenv'
brew 'rbenv'
brew 'jenv'
brew 'direnv'
brew 'nodenv'
brew 'tfenv'
brew 'tflint'
brew 'goenv', args: ['HEAD']

# Cask Applications
cask 'alfred'
cask 'caffeine'
cask 'docker'
# cask 'dash'
cask 'dropbox'
cask 'emacs'
cask 'lastpass'
cask 'iterm2'
cask 'karabiner-elements'
cask 'kindle'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'slack'
cask 'skitch'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'wireshark'
cask 'xmind'

# AppStore Applications
mas "LINE", id: 539883307
mas "Pocket", id: 568494494
mas "Twitter", id: 1482454543
mas "Evernote", id: 406056744
