tap 'homebrew/core'
tap 'homebrew/cask'
tap 'sanemat/font'

# tools
brew 'ansifilter'
brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'findutils'
brew 'gettext'
brew 'ghq'
brew 'hub'
brew 'jq'
brew 'peco'
brew 'readline'
brew 'ssh-copy-id'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'ack'
brew 'mas'

# fonts
brew 'sanemat/font/ricty', args: ['with-powerline']

# Shell integrations
brew 'reattach-to-user-namespace'
brew 'source-highlight'
brew 'tmux'
brew 'z'
brew 'zplug'
brew 'zsh'

# Programming languages
brew 'clang-format'
brew 'plenv'
brew 'pyenv'
brew 'rbenv'
brew 'jenv'
brew 'direnv'
brew 'nodenv'
brew 'tfenv'
brew 'goenv', args: ['HEAD']

# Cask Applications
cask '1password'
cask 'alfred'
cask 'caffeine'
cask 'docker'
cask 'dropbox'
cask 'emacs'
cask 'iterm2'
cask 'karabiner-elements'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'slack'
cask 'skitch'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'wireshark'

# AppStore Applications
mas "LINE", id: 539883307
mas "Pocket", id: 568494494
mas "Twitter", id: 1482454543
